import { ArrowUpRight } from "lucide-react";
import { MarketingShell, SectionLabel } from "@/components/SiteChrome";
import { SeoHead } from "@/components/SeoHead";
import { trpc } from "@/lib/trpc";

export default function CaseStudies() {
  const records = trpc.caseStudies.listPublic.useQuery();
  return <MarketingShell><SeoHead title="Evidence-Led Case Studies | Coreweaver Labs" description="Coreweaver Labs publishes case studies only when scope, source evidence, reporting windows, review dates, safety checks, and written authorization are complete." path="/case-studies" /><main><section className="case-studies-hero section-pad"><SectionLabel>Case studies</SectionLabel><p className="page-kicker">Evidence before narrative</p><h1>Useful proof has a record behind it.</h1><p className="page-lede">Every published case study must identify an approved client label, source, supportable finding, scope, reporting window, review date, safety checks, and written authorization.</p></section><section className="case-standards section-pad section-rule"><div><SectionLabel>Publication standard</SectionLabel><h2>A public story begins with an approved record.</h2></div><div className="case-standard-list"><p><b>Source attribution</b> The supporting source is identified at the level publication authorization permits.</p><p><b>Reporting discipline</b> The reporting window, metric context when relevant, and evidence review date are visible on every approved story.</p><p><b>Authorization gate</b> Nothing is published from an intake record until the approved wording, privacy, and safety checks are confirmed.</p></div></section>{records.data?.length ? <section className="case-records section-pad section-rule"><SectionLabel>Approved records</SectionLabel><div className="case-record-grid">{records.data.map(record => <a className="case-record-card" key={record.id} href={`/case-studies/${record.slug}`}><p className="page-kicker">{record.clientLabel}</p><h2>{record.title}</h2><p>{record.supportableFinding}</p><span>Read approved record <ArrowUpRight size={15} /></span></a>)}</div></section> : <section className="case-preview-card section-pad section-rule"><div><SectionLabel>Evidence pending</SectionLabel><h2>No client-results record is approved for public display.</h2><p>The evidence ledger remains empty until a complete approval worksheet, privacy review, and source-supported public record have cleared review.</p></div><a className="button button-primary" href="/case-studies/governance-preview">Open governance preview <ArrowUpRight size={16} /></a></section>}</main></MarketingShell>;
}
